/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio2;

import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class ConversorDeTemperatura extends javax.swing.JFrame {

    /**
     * Creates new form ConversorDeTemperatura
     */
    public ConversorDeTemperatura() {
        initComponents();
        grupoBotones.add(botonFahren);
        grupoBotones.add(botonKelvin);
        grupoBotones.add(botonRadianes);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        grupoBotones = new javax.swing.ButtonGroup();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jtCelcius = new javax.swing.JTextField();
        TextoLabel = new javax.swing.JLabel();
        botonFahren = new javax.swing.JRadioButton();
        botonKelvin = new javax.swing.JRadioButton();
        botonRadianes = new javax.swing.JRadioButton();
        botonConvertir = new javax.swing.JButton();
        tituloLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor");

        jtCelcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCelciusActionPerformed(evt);
            }
        });

        TextoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TextoLabel.setText("Ingrese la Temperatura en Grados Celsius");

        botonFahren.setText("Fahrenheit");
        botonFahren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFahrenActionPerformed(evt);
            }
        });

        botonKelvin.setText("Kelvin");
        botonKelvin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonKelvinActionPerformed(evt);
            }
        });

        botonRadianes.setText("Radianes");
        botonRadianes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRadianesActionPerformed(evt);
            }
        });

        botonConvertir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ejercicio2/iconos/output-onlinepngtools.png"))); // NOI18N
        botonConvertir.setText("Convertir");
        botonConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConvertirActionPerformed(evt);
            }
        });

        tituloLabel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        tituloLabel.setText("Conversor de Temperatura");
        tituloLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(TextoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonFahren)
                        .addGap(40, 40, 40)
                        .addComponent(botonKelvin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonRadianes))
                    .addComponent(tituloLabel))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonConvertir)
                    .addComponent(jtCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(tituloLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonKelvin)
                    .addComponent(botonRadianes)
                    .addComponent(botonFahren))
                .addGap(18, 18, 18)
                .addComponent(botonConvertir)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jDesktopPane2.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane2Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtCelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCelciusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtCelciusActionPerformed

    private void botonConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConvertirActionPerformed
        try {
            if (botonFahren.isSelected()) {
                double temperatura = Double.parseDouble(jtCelcius.getText());
                temperatura = (temperatura * 9 / 5) + 32;
                JOptionPane.showMessageDialog(null, "La Temperatura en Fahrenheit es: " + temperatura);
            } else if (botonRadianes.isSelected()) {
                double temperatura = Double.parseDouble(jtCelcius.getText());
                temperatura = (temperatura * (3.14 / 180));
                JOptionPane.showMessageDialog(null, "La Temperatura en Radianes es: " + temperatura);
            } else if (botonKelvin.isSelected()) {
                double gradosKelvin = 273.15;
                double gradosCelsius = Double.parseDouble(jtCelcius.getText());
                double convertorDeGradosCelciusAKelvin = gradosCelsius + gradosKelvin;
                JOptionPane.showMessageDialog(null, "La Temperatura en Kelvin es: " + convertorDeGradosCelciusAKelvin);
            }
        } catch (NumberFormatException nfe1) {
            JOptionPane.showMessageDialog(this, "El formato ingresado es incorrecto, Debe ingresar numeros.");
        }
    }//GEN-LAST:event_botonConvertirActionPerformed

    private void botonRadianesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRadianesActionPerformed

    }//GEN-LAST:event_botonRadianesActionPerformed

    private void botonKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonKelvinActionPerformed

    }//GEN-LAST:event_botonKelvinActionPerformed

    private void botonFahrenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFahrenActionPerformed

    }//GEN-LAST:event_botonFahrenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorDeTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorDeTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorDeTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorDeTemperatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorDeTemperatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextoLabel;
    private javax.swing.JButton botonConvertir;
    private javax.swing.JRadioButton botonFahren;
    private javax.swing.JRadioButton botonKelvin;
    private javax.swing.JRadioButton botonRadianes;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtCelcius;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
